
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
from tkinter import ttk # it allow us to create combobox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\User\Courses\Almacenes de datos\Todo lo relacionado al proyecto\Proyecto\almacenes_project\assets\frame0")
# tenemos que buscar el path donde esta el frame0

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

# importamos pandas para poder leer el dataset
import pandas as pd
file_path = "BankOfAmericaCredits.csv"
df = pd.read_csv(file_path)
def bayes():
    # Obtenemos los valores
    gender = entry_1.get()
    Income = entry_2.get()
    employee = entry_3.get()
    debt = entry_4.get()
    driver = entry_5.get()
    age = entry_6.get()
    citizen = entry_7.get()
    prior_default = entry_8.get()
    industry = entry_9.get()
    credit_score = entry_10.get()
    bank_customer = entry_11.get()
    ethnicity = entry_12.get()
    years_employed = entry_13.get()
    
    

    # definimos una variable "target" (x es el resto de las columnas, "y" la variable que queremos conocer)
    target = "Approved"
    x = df.drop(target, axis=1)
    y = df[target]

    # seleccionamos nuestros conjuntos de entrenamiento y prueba 
    from sklearn.model_selection import train_test_split
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

    # creamos un algoritmo
    from sklearn.naive_bayes import GaussianNB
    method = GaussianNB()

    # entrenamos el modelo
    method.fit(x_train,y_train)

    # creamos un data frame
    data = {
    'Gender': [gender],
    'Income': [Income],
    'CreditScore': [credit_score],
    'BankCustomer': [bank_customer],
    'Industry': [industry],
    'Ethnicity': [ethnicity],
    'YearsEmployed': [years_employed],
    'PriorDefault': [prior_default],
    'Employed': [employee],
    'Debt': [debt],
    'DriversLicense': [driver],
    'Age': [age],
    'Citizen': [citizen]
    }

    #Crear el DataFrame
    client = pd.DataFrame(data)

    #predice el resultado
    pred = method.predict(client)

    if pred[0] == 1:
        messagebox.showinfo("Felicidades", "Su credito fue APROBADO")
    else:
        messagebox.showinfo("Lo sentimos", "Su credito fue RECHAZADO")
    
    # creamos el grafico 
    # import matplotlib.pyplot as plt
    # sns.countplot(x='Approved', data=df)
    # plt.show()
    


def del_entry():
    entries = [entry_2, entry_3, entry_4, entry_5, entry_6, entry_7, entry_8, entry_9, entry_10, entry_11, entry_12, entry_13] 
    #falta entry_1

    for entry in entries:
        entry.delete(0, 'end')

window.geometry("774x702")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 702,
    width = 774,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    386.67657470703125,
    54.968902587890625,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    120.0,
    396.972412109375,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    491.143798828125,
    357.6100158691406,
    image=image_image_3
)

from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import seaborn as sns

fig = Figure(figsize=(4.5, 4.4), dpi=100, facecolor=("#0073CF"))
plot = fig.add_subplot(1, 1, 1)
sns.countplot(x='Approved', data=df, ax=plot)

canvasf = FigureCanvasTkAgg(fig, master=window)  # A 'master' is the parent widget.
canvasf.draw()
canvasf.get_tk_widget().place(x=261, y=136)

canvas.create_text(
    27.74017333984375,
    131.7417755126953,
    anchor="nw",
    text="Género",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

# entry_image_1 = PhotoImage(
#     file=relative_to_assets("entry_1.png"))
# entry_bg_1 = canvas.create_image(
#     120.38753509521484,
#     161.08596801757812,
#     image=entry_image_1
# )
# entry_1 = Entry(
#     bd=0,
#     bg="#FFFCFC",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_1.place(
#     x=42.12137198448181,
#     y=153.11705017089844,
#     width=156.53232622146606,
#     height=13.937835693359375
# )
entry_1 = ttk.Combobox(
    canvas,
    values=("","Hombre","Mujer"),
)
entry_1.place(
    x=42.12137198448181,
    y=153.11705017089844,
    width=156.53232622146606,
    height=18.937835693359375
)
entry_1.current(0)

canvas.create_text(
    27.74017333984375,
    169.8844757080078,
    anchor="nw",
    text="Ingreso",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    120.38753509521484,
    199.79214477539062,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=42.12137198448181,
    y=191.82322692871094,
    width=156.53232622146606,
    height=13.937835693359375
)

canvas.create_text(
    30.2894287109375,
    472.6804504394531,
    anchor="nw",
    text="Empleado",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    29.15106201171875,
    512.5250244140625,
    anchor="nw",
    text="Deudas",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    29.0,
    551.7044677734375,
    anchor="nw",
    text="Licencia de conducir",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    30.2894287109375,
    591.64501953125,
    anchor="nw",
    text="Edad",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    29.0,
    632.3243408203125,
    anchor="nw",
    text="Ciudadano",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

# entry_image_3 = PhotoImage(
#     file=relative_to_assets("entry_3.png"))
# entry_bg_3 = canvas.create_image(
#     121.6473617553711,
#     502.27931213378906,
#     image=entry_image_3
# )
# entry_3 = Entry(
#     bd=0,
#     bg="#FFFCFC",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_3.place(
#     x=43.38119864463806,
#     y=494.3103942871094,
#     width=156.53232622146606,
#     height=13.937835693359375
# )
entry_3 = ttk.Combobox(
    canvas,
    values=("","Si","No"),
)
entry_3.place(
    x=43.38119864463806,
    y=494.3103942871094,
    width=156.53232622146606,
    height=18.937835693359375
)
entry_3.current(0)


entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    121.6473617553711,
    540.7008543014526,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=43.38119864463806,
    y=533.0165405273438,
    width=156.53232622146606,
    height=13.368627548217773
)

# entry_image_5 = PhotoImage(
#     file=relative_to_assets("entry_5.png"))
# entry_bg_5 = canvas.create_image(
#     122.2165756225586,
#     580.5455198287964,
#     image=entry_image_5
# )
# entry_5 = Entry(
#     bd=0,
#     bg="#FFFCFC",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_5.place(
#     x=43.95041251182556,
#     y=572.8612060546875,
#     width=156.53232622146606,
#     height=13.368627548217773
# )

entry_5 = ttk.Combobox(
    canvas,
    values=("","Si","No"),
)
entry_5.place(
    x=43.95041251182556,
    y=572.8612060546875,
    width=156.53232622146606,
    height=18.937835693359375
)
entry_5.current(0)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    121.6473617553711,
    622.3822479248047,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=43.38119864463806,
    y=614.413330078125,
    width=156.53232622146606,
    height=13.937835693359375
)

# entry_image_7 = PhotoImage(
#     file=relative_to_assets("entry_7.png"))
# entry_bg_7 = canvas.create_image(
#     121.6473617553711,
#     660.0961790084839,
#     image=entry_image_7
# )
# entry_7 = Entry(
#     bd=0,
#     bg="#FFFCFC",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_7.place(
#     x=43.38119864463806,
#     y=652.411865234375,
#     width=156.53232622146606,
#     height=13.368627548217773
# )

entry_7 = ttk.Combobox(
    canvas,
    values=("","Si","No"),
)
entry_7.place(
    x=43.38119864463806,
    y=652.411865234375,
    width=156.53232622146606,
    height=18.937835693359375
)
entry_7.current(0)

canvas.create_text(
    29.0,
    433.6804504394531,
    anchor="nw",
    text="Credito anterior",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

entry_8 = ttk.Combobox(
    canvas,
    values=("","Si","No"),
)
entry_8.place(
    x=43.38119864463806,
    y=453.7680358886719,
    width=156.53232622146606,
    height=18.937835693359375
)
entry_8.current(0)

# entry_image_8 = PhotoImage(
#     file=relative_to_assets("entry_8.png"))
# entry_bg_8 = canvas.create_image(
#     121.6473617553711,
#     461.45234966278076,
#     image=entry_image_8
# )
# entry_8 = Entry(
#     bd=0,
#     bg="#FFFCFC",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_8.place(
#     x=43.38119864463806,
#     y=453.7680358886719,
#     width=156.53232622146606,
#     height=13.368627548217773
# )

canvas.create_text(
    29.0,
    301.972412109375,
    anchor="nw",
    text="Industria",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

# entry_image_9 = PhotoImage(
#     file=relative_to_assets("entry_9.png"))
# entry_bg_9 = canvas.create_image(
#     123.0,
#     331.472412109375,
#     image=entry_image_9
# )
# entry_9 = Entry(
#     bd=0,
#     bg="#FFFCFC",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_9.place(
#     x=45.84604239463806,
#     y=323.972412109375,
#     width=154.30791521072388,
#     height=13.0
#)

entry_9 = ttk.Combobox(
    canvas,
    values=("",'comunicacion','entretenimiento','agropecuario','educacion','energia','finanzas','salud','industrial','tecnologia','materiales',
            'bienes raices','investigacion','transporte','gobierno'),
)
entry_9.place(
    x=45.84604239463806,
    y=323.972412109375,
    width=156.53232622146606,
    height=18.937835693359375
)
entry_9.current(0)

canvas.create_text(
    28.6070556640625,
    214.96221923828125,
    anchor="nw",
    text="Puntaje de Credito",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    120.38753509521484,
    245.044207572937,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=42.12137198448181,
    y=237.35989379882812,
    width=156.53232622146606,
    height=13.368627548217773
)

canvas.create_text(
    29.02960205078125,
    260.12823486328125,
    anchor="nw",
    text="Cliente",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

# entry_image_11 = PhotoImage(
#     file=relative_to_assets("entry_11.png"))
# entry_bg_11 = canvas.create_image(
#     121.24142456054688,
#     289.7270965576172,
#     image=entry_image_11
# )
# entry_11 = Entry(
#     bd=0,
#     bg="#FFFCFC",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_11.place(
#     x=43.82907462120056,
#     y=281.7581787109375,
#     width=154.82469987869263,
#     height=13.937835693359375
# )

entry_11 = ttk.Combobox(
    canvas,
    values=("","Si","No"),
)
entry_11.place(
   x=43.82907462120056,
   y=281.7581787109375,
    width=156.53232622146606,
    height=18.937835693359375
)
entry_11.current(0)

canvas.create_text(
    28.0,
    345.972412109375,
    anchor="nw",
    text="Etnia",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    29.0,
    391.972412109375,
    anchor="nw",
    text="Años Trabajando",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

# entry_image_12 = PhotoImage(
#     file=relative_to_assets("entry_12.png"))
# entry_bg_12 = canvas.create_image(
#     120.21182250976562,
#     375.5712432861328,
#     image=entry_image_12
# )
# entry_12 = Entry(
#     bd=0,
#     bg="#FFFCFC",
#     fg="#000716",
#     highlightthickness=0
# )
# entry_12.place(
#     x=42.79947257041931,
#     y=367.6023254394531,
#     width=154.82469987869263,
#     height=13.937835693359375
# )

entry_12 = ttk.Combobox(
    canvas,
    values=("",'asiatico', 'negro', 'latino', 'otro', 'blanco'
            ),
)
entry_12.place(
    x=42.79947257041931,
    y=367.6023254394531,
    width=156.53232622146606,
    height=18.937835693359375
)
entry_12.current(0)

entry_image_13 = PhotoImage(
    file=relative_to_assets("entry_13.png"))
entry_bg_13 = canvas.create_image(
    121.6473617553711,
    421.2066526412964,
    image=entry_image_13
)
entry_13 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_13.place(
    x=43.38119864463806,
    y=413.5223388671875,
    width=156.53232622146606,
    height=13.368627548217773
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=bayes, #invocamos la funcion de bayes
    relief="flat"
)
button_1.place(
    x=256.0,
    y=615.972412109375,
    width=211.74554443359375,
    height=63.41462326049805
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=del_entry, #invocamos la funcion de del_entry
    relief="flat"
)
button_2.place(
    x=511.0,
    y=615.972412109375,
    width=217.45480346679688,
    height=64.0
)
window.resizable(False, False)
window.mainloop()
