
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\User\Courses\Almacenes de datos\Todo lo relacionado al proyecto\Proyecto\almacenes_project\assets\frame0")
# tenemos que buscar el path donde esta el frame0

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("774x702")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 702,
    width = 774,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    386.67657470703125,
    54.968902587890625,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    119.36865234375,
    356.39532470703125,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    491.143798828125,
    357.6100158691406,
    image=image_image_3
)

canvas.create_text(
    27.74017333984375,
    131.7417755126953,
    anchor="nw",
    text="Género",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    120.38753509521484,
    161.08596801757812,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=42.12137198448181,
    y=153.11705017089844,
    width=156.53232622146606,
    height=13.937835693359375
)

canvas.create_text(
    27.74017333984375,
    169.8844757080078,
    anchor="nw",
    text="Ingreso",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    120.38753509521484,
    199.79214477539062,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=42.12137198448181,
    y=191.82322692871094,
    width=156.53232622146606,
    height=13.937835693359375
)

canvas.create_text(
    29.02960205078125,
    388.20013427734375,
    anchor="nw",
    text="Empleado",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    27.8912353515625,
    428.04473876953125,
    anchor="nw",
    text="Deudas",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    27.74017333984375,
    467.22418212890625,
    anchor="nw",
    text="Licencia de conducir",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    29.02960205078125,
    507.1646728515625,
    anchor="nw",
    text="Edad",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    27.74017333984375,
    547.843994140625,
    anchor="nw",
    text="Ciudadano",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    120.38753509521484,
    417.7989959716797,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=42.12137198448181,
    y=409.830078125,
    width=156.53232622146606,
    height=13.937835693359375
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    120.38753509521484,
    456.22053813934326,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=42.12137198448181,
    y=448.5362243652344,
    width=156.53232622146606,
    height=13.368627548217773
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    120.95674896240234,
    496.06514263153076,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=42.69058585166931,
    y=488.3808288574219,
    width=156.53232622146606,
    height=13.368627548217773
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    120.38753509521484,
    537.9019622802734,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=42.12137198448181,
    y=529.9330444335938,
    width=156.53232622146606,
    height=13.937835693359375
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    120.38753509521484,
    574.6158933639526,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=42.12137198448181,
    y=566.9315795898438,
    width=156.53232622146606,
    height=13.368627548217773
)

canvas.create_text(
    28.6070556640625,
    214.96221923828125,
    anchor="nw",
    text="Puntaje de Credito",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    120.38753509521484,
    245.044207572937,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=42.12137198448181,
    y=237.35989379882812,
    width=156.53232622146606,
    height=13.368627548217773
)

canvas.create_text(
    29.02960205078125,
    260.12823486328125,
    anchor="nw",
    text="Cliente",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    121.24142456054688,
    289.7270965576172,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=43.82907462120056,
    y=281.7581787109375,
    width=154.82469987869263,
    height=13.937835693359375
)

canvas.create_text(
    29.02960205078125,
    301.6804504394531,
    anchor="nw",
    text="Etnia",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

canvas.create_text(
    27.74017333984375,
    346.7279052734375,
    anchor="nw",
    text="Años Trabajando",
    fill="#FFFFFF",
    font=("Lato Bold", 17 * -1)
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    121.24142456054688,
    331.27928161621094,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=43.82907462120056,
    y=323.31036376953125,
    width=154.82469987869263,
    height=13.937835693359375
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    120.38753509521484,
    375.9621458053589,
    image=entry_image_11
)
entry_11 = Entry(
    bd=0,
    bg="#FFFCFC",
    fg="#000716",
    highlightthickness=0
)
entry_11.place(
    x=42.12137198448181,
    y=368.27783203125,
    width=156.53232622146606,
    height=13.368627548217773
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=96.0,
    y=617.972412109375,
    width=211.74554443359375,
    height=63.41462326049805
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=482.54248046875,
    y=617.972412109375,
    width=217.45480346679688,
    height=64.0
)
window.resizable(False, False)
window.mainloop()
